# Generated by Django 4.1.7 on 2023-03-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Artist Name'),
        ),
    ]
